### PR TITLE
Fix comment search highlight + multi-word search

### LINKED ISSUE #2536: [BUG] Multi-word comment search strings not working in 1.12.1
### Description

if 1 word is searched in advanced search "example" paperless will find the word in commits

if 2 words are searched in commits "example two" this ends in error:
Fehler beim Laden des Dokuments: 'Or' object has no attribute 'text'
capture_001_27012023_135402
capture_001_27012023_140154

### Steps to reproduce

Go to expanded search
search 2 words
error occured

### Webserver logs

```bash
no related logs
```

### Browser logs

_No response_

### Paperless-ngx version

1.12.1

### Host OS

Docker official Synologie NAS

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

_No response_

### Other

_No response_

### PR DESCRIPTION
**Pull request by shamoon**
## Proposed change

Fixes the issue with searching for multi-word comments and fixes some issues that can with comment search highlighting.

Comment searching has proved to be a bit more complicated than I realized, honestly mostly because I find the whoosh docs to be opaque, but thats on me. The fix here is mostly to let whoosh handle the highlighting on its own instead of trying to mess with it. I also took the opportunity to allow for visual highlighting more than one comment. See screenshots of all

Screen Shot 2023-01-27 at 10 28 39 AM
Screen Shot 2023-01-27 at 10 01 22 AM
Screen Shot 2023-01-27 at 10 01 15 AM

Fixes #2536

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (please explain)

## Checklist:

- [x] I have read & agree with the [contributing guidelines](https://github.com/paperless-ngx/paperless-ngx/blob/main/CONTRIBUTING.md).
- [x] If applicable, I have tested my code for new features & regressions on both mobile & desktop devices, using the latest version of major browsers.
- [x] If applicable, I have checked that all tests pass, see [documentation](https://docs.paperless-ngx.com/development/#back-end-development).
- [x] I have run all `pre-commit` hooks, see [documentation](https://docs.paperless-ngx.com/development/#code-formatting-with-pre-commit-hooks).
- [ ] ~~I have made corresponding changes to the documentation as needed.~~
- [x] I have checked my modifications for any breaking changes.

### CODE REVIEW

**Review by stumpylog — APPROVED** [review]
I also find Whoosh to be difficcult reading.
