### ISSUE TITLE
[BUG] CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED

### ISSUE THREAD

**Issue by TaoChan1005** [paperless-ngx/paperless-ngx#3955]
### Description

after i upgrade to 1.17.0, when I upload a PDF file, it failed.

error infomation is :'Settings' object has no attribute 'CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED'

<img width="1172" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/42793494/5852b012-0e96-4563-b18e-58cecaab6471">

### Steps to reproduce

upload file

### Webserver logs

```bash
[2023-08-08 11:05:09,064] [DEBUG] [paperless.classifier] Gathering data from database...

[2023-08-08 11:05:09,373] [DEBUG] [paperless.tasks] Training data unchanged.

[2023-08-08 11:18:55,649] [INFO] [paperless.management.consumer] Received SIGINT, stopping inotify

[2023-08-08 11:18:55,802] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2023-08-08 11:19:17,186] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
```

### Paperless-ngx version

1.17.0

### Host OS

debian-11

### Installation method

Docker - official image

**Comment by TaoChan1005** [comment]
version-1.16 works

**Comment by stumpylog** [comment]
Your log doesn't actually show this error.  Please provide a log with the error and traceback.  And please note any configuration changes made.

**Comment by shamoon** [comment]
Yea this can't be right, consuming docs is not completely broken and that var does exist https://github.com/paperless-ngx/paperless-ngx/blob/b961df90a72f506f4a58c236fd3712cebb1523ff/src/paperless/settings.py#L795-L797

**Comment by TaoChan1005** [comment]
> Your log doesn't actually show this error. Please provide a log with the error and traceback. And please note any configuration changes made.
```
paperless  | HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE paperless REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
paperless  | [2023-08-08 22:02:20,165] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[7d0accf8-d9bf-45dc-b557-822a857261f3] received
paperless  | WARNING:  database "paperless" has a collation version mismatch
paperless  | DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.36.
paperless  | HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE paperless REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
paperless  | WARNING:  database "paperless" has a collation version mismatch
paperless  | DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.36.
paperless  | HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE paperless REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.
paperless  | [2023-08-08 22:02:20,248] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[7d0accf8-d9bf-45dc-b557-822a857261f3] raised unexpected: AttributeError("'Settings' object has no attribute 'CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED'")
paperless  | Traceback (most recent call last):
paperless  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
paperless  |     R = retval = fun(*args, **kwargs)
paperless  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 760, in __protected_call__
paperless  |     return self.run(*args, **kwargs)
paperless  |   File "/usr/src/paperless/src/documents/tasks.py", line 121, in consume_file
paperless  |     if settings.CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED and (
paperless  |   File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 94, in __getattr__
paperless  |     val = getattr(_wrapped, name)
paperless  | AttributeError: 'Settings' object has no attribute 'CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED'
```

**Comment by TaoChan1005** [comment]
Where can I fin the new config example?

**Comment by stumpylog** [comment]
>  DETAIL:  The database was created using collation version 2.31, but the operating system provides version 2.36. 

That reads like a database version was updated without upgrading the on disk files.  Major version upgrades between Postgres require special attention.

> AttributeError: 'Settings' object has no attribute 'CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED'

I would suggest re-pulling and re-creating, the setting exists and I cannot reproduce this with 1.17, or after a 1.16 to 1.17 upgrade.

**Comment by TaoChan1005** [comment]
this is my fault. I mount 'setting.py' which i modified some contents to the docker
