### ISSUE TITLE
[BUG] Tika tests fail with tika-client==0.1.0

### ISSUE THREAD

**Issue by e1mo** [paperless-ngx/paperless-ngx#3619]
### Description

With `tika-client==0.1.0` (which is allowed by the Pipfile) various paperless tests around the tika implementation fail that were working fine with `tika-client==0.3.0`.

       > FAILED src/paperless_mail/tests/test_parsers.py::TestTikaHtmlParse::test_tika_parse_unsuccessful - documents.parsers.ParseError: Could not parse content with tika server at h...
       > FAILED src/paperless_mail/tests/test_parsers.py::TestParser::test_generate_pdf_html_email - documents.parsers.ParseError: Could not parse content with tika server at h...
       > FAILED src/paperless_mail/tests/test_parsers.py::TestParser::test_parse_eml_html - documents.parsers.ParseError: Could not parse content with tika server at h...
       > FAILED src/paperless_tika/tests/test_tika_parser.py::TestTikaParser::test_parse - AttributeError: 'ParsedDocument' object has no attribute 'metadata'
       > ERROR src/paperless_mail/tests/test_parsers.py::TestParser::test_generate_pdf_html_email_html_to_pdf_failure - AssertionError: The following responses are mocked but not requested:
       > ERROR src/paperless_mail/tests/test_parsers.py::TestParser::test_generate_pdf_html_email_merge_failure - AssertionError: The following responses are mocked but not requested:
       > ERROR src/paperless_mail/tests/test_parsers.py::TestParser::test_generate_pdf_html_email - AssertionError: The following responses are mocked but not requested:
       > ERROR src/paperless_tika/tests/test_tika_parser.py::TestTikaParser::test_parse - AssertionError: The following responses are mocked but not requested:
       > 5 failed, 730 passed, 12 skipped, 59 warnings, 4 errors in 161.77s (0:02:41)
       > /nix/store/0swa08bbslxc9wbfixbcd196aa1117lx-stdenv-linux/setup: line 1586: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/y3mq2i4d3rv9j4bc461r86rhjrc5n45c-paperless-ngx-1.16.1.drv'.

### Steps to reproduce

1. Install paperless with the (currently) latest version of `tika-client==0.1.0`
2. Run `pytest`
3. Notice failing tests
4. Downgrade to `tika-client=0.0.3`, run `pytest`
5. Tests now succeed
The nixpkgs PR containing the override to actually use `0.0.3` (which can be commented out to test it with `0.1.0`) can be found (soon™) at https://github.com/NixOS/nixpkgs/pull/232210

### Webserver logs

Webserver logs are not applicable here, but the full test logs can be found at: https://gist.github.com/e1mo/d195b2574cfd02f8e0a145908d8d2169

### Paperless-ngx version

1.16.1

### Host OS

NixOS, x86_64

### Installation method

Bare metal

### Other

I am aware that the current Pipfile.lock pins paperless to using 0.0.3, however I see this as waiting breakage and wanted to bring it up as such.

**Comment by stumpylog** [comment]
There's a draft pr
