### ISSUE TITLE
[BUG] Update from v2.20.15 to 3.0.5 paperless-webserver AttributeError: 'datetime.date' object has no attribute 'utcoffset'

### ISSUE THREAD

**Issue by manni-2x** [paperless-ngx/paperless-ngx#13882]
### Description

After update from v2.20.15 to 3.0.5 paperless-webserver restarts in endless loop with AttributeError: 'datetime.date' object has no attribute 'utcoffset' .
See log below. 
DB (unchanged):
PAPERLESS_DBENGINE: mariadb
PAPERLESS_DBHOST: db

### Steps to reproduce

1. Update from v2.20.15 to 3.0.5
2. See log in container - restarts in endless loop

### Webserver logs

```bash
Running Django checks

System check identified no issues (0 silenced).

Search index out of date. Updating...

Traceback (most recent call last):

  File "/usr/src/paperless/src/manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute

    output = self.handle(*args, **options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/management/commands/document_index.py", line 20, in handle

    index_reindex(progress_bar_disable=self.no_progress_bar)

  File "/usr/src/paperless/src/documents/tasks.py", line 66, in index_reindex

    for document in tqdm.tqdm(documents, disable=progress_bar_disable):

  File "/usr/local/lib/python3.11/site-packages/tqdm/std.py", line 1169, in __iter__

    for obj in iterable:

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 121, in __iter__

    for row in compiler.results_iter(results):

  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1500, in apply_converters

    value = converter(value, expression, connection)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/operations.py", line 331, in convert_datetimefield_value

    value = timezone.make_aware(value, self.connection.timezone)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/timezone.py", line 290, in make_aware

    if is_aware(value):

       ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/timezone.py", line 256, in is_aware

    return value.utcoffset() is not None

           ^^^^^^^^^^^^^^^

AttributeError: 'datetime.date' object has no attribute 'utcoffset'

Paperless-ngx docker container starting...

Installing languages...

Hit:1 http://deb.debian.org/debian bookworm InRelease

Hit:2 http://deb.debian.org/debian bookworm-updates InRelease

Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease

Reading package lists...

Package tesseract-ocr-deu already installed!

Package tesseract-ocr-eng already installed!

Creating directory scratch directory /tmp/paperless

Adjusting permissions of paperless files. This may take a while.

Waiting for MariaDB to start...

Waiting for Redis...

Connected to Redis broker.

Apply database migrations...

Operations to perform:

  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount

Running migrations:

  No migrations to apply.

Running Django checks

System check identified no issues (0 silenced).

Search index out of date. Updating...

Traceback (most recent call last):

  File "/usr/src/paperless/src/manage.py", line 10, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute

    output = self.handle(*args, **options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/management/commands/document_index.py", line 20, in handle

    index_reindex(progress_bar_disable=self.no_progress_bar)

  File "/usr/src/paperless/src/documents/tasks.py", line 66, in index_reindex

    for document in tqdm.tqdm(documents, disable=progress_bar_disable):

  File "/usr/local/lib/python3.11/site-packages/tqdm/std.py", line 1169, in __iter__

    for obj in iterable:

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__

    self._fetch_all()

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all

    self._result_cache = list(self._iterable_class(self))

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 121, in __iter__

    for row in compiler.results_iter(results):

  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1500, in apply_converters

    value = converter(value, expression, connection)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/mysql/operations.py", line 331, in convert_datetimefield_value

    value = timezone.make_aware(value, self.connection.timezone)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/timezone.py", line 290, in make_aware

    if is_aware(value):

       ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/django/utils/timezone.py", line 256, in is_aware

    return value.utcoffset() is not None

           ^^^^^^^^^^^^^^^

AttributeError: 'datetime.date' object has no attribute 'utcoffset'
```

### Browser logs

```bash

```

### Services logs

```bash

```

### Paperless-ngx version

3.0.5

### Host OS

Synology OS, uname -m x86_64

### Installation method

Docker - official image

### System status

```json

```

### Browser

edge

### Configuration changes

removed: 
#PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING   # v3 zxing-cpp is now the only backend

### Please confirm the following

- [x] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [x] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [x] I have already searched for relevant existing issues and discussions before opening this report.
- [x] I have updated the title field above with a concise description.

**Comment by shamoon** [comment]
This container is not running v3.0.5 (easily seen if you had provided full logs). v3.0.5 uses Python 3.12 and no longer has `documents.tasks.index_reindex` and theres Whoosh-era code. Make sure you have pulled correctly, force-recreated the container etc. This is not a bug.

**Comment by manni-2x** [comment]
I'm using compose data with  image: ghcr.io/paperless-ngx/paperless-ngx:latest and update stack in portainer. There is no force option?

**Comment by shamoon** [comment]
Thats really just a portainer question, https://share.google/aimode/bpdVPZnbcPzhjYt5c
