### ISSUE TITLE
[BUG] Mail account login via STARTTLS broken

### ISSUE THREAD

**Issue by Kurocon** [paperless-ngx/paperless-ngx#697]
### Description

Mail account login via STARTTLS is broken. See the error in the log file.

### Expected behavior

STARTTLS mail accounts should work normally

### Steps to reproduce

1. Setup a mail account with STARTTLS security and enable a mail rule for synchronization
2. Wait for the task to trigger

### Webserver logs

```bash
10:52:20 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
10:52:20 [Q] INFO Process-1:13 processing [wisconsin-music-enemy-sierra]
10:52:20 [Q] INFO Process-1:13 stopped doing work
10:52:20 [Q] ERROR Failed [wisconsin-music-enemy-sierra] - __init__() got an unexpected keyword argument 'starttls' : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/paperless_mail/tasks.py", line 15, in process_mail_accounts
    total_new_documents += MailAccountHandler().handle_mail_account(account)
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 158, in handle_mail_account
    with get_mailbox(
  File "/usr/src/paperless/src/paperless_mail/mail.py", line 95, in get_mailbox
    mailbox = MailBox(server, port, starttls=True)
TypeError: __init__() got an unexpected keyword argument 'starttls'

10:52:21 [Q] INFO recycled worker Process-1:13
10:52:21 [Q] INFO Process-1:17 ready for work at 574
```

### Paperless-ngx version

1.7.0-rc1

### Host OS

Debian 11

### Installation method

Docker

### Browser

Firefox

### Configuration changes

n.a.

**Comment by gador** [comment]
could you add a debug output as well?
Has it worked with ngx-1.6.0 before?

**Comment by qcasey** [comment]
This was a breaking change in imap-tools 52:

https://github.com/ikvk/imap_tools/releases/tag/v0.52.0

Bumped here in #236. This will need to be fixed

**Comment by gador** [comment]
I'm working on it right now

**Comment by gador** [comment]
ok, please see #705

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/045a401cd76eab635902a746e599d83683e5d655
