### ISSUE TITLE
[BUG] Multi-word comment search strings not working in 1.12.1

### ISSUE THREAD

**Issue by muecke6** [paperless-ngx/paperless-ngx#2536]
### Description

if 1 word is searched in advanced search "example" paperless will find the word in commits

if 2 words are searched in commits "example two" this ends in error:
Fehler beim Laden des Dokuments: 'Or' object has no attribute 'text'
![capture_001_27012023_135402](https://user-images.githubusercontent.com/123741690/215092032-520a101d-cf42-4a98-b6bb-0f04b5ba2af7.jpg)
![capture_001_27012023_140154](https://user-images.githubusercontent.com/123741690/215093269-14da0143-e534-4fc8-b7b0-b98070ce16d9.jpg)

### Steps to reproduce

Go to expanded search
search 2 words
error occured

### Webserver logs

```bash
no related logs
```

### Paperless-ngx version

1.12.1

### Host OS

Docker official Synologie NAS

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment]
Ah thanks, I will track this one down

**Comment by shamoon** [comment]
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/d2b290f78998091a141db4dacbb77e9bffdd411d
